[package]
name = "kessard2"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
reqwest = "0.11.14"
reqwest-middleware = "0.2.0"
rocket = { version="0.5.0-rc.2", features=["json"] }
tokio = { version="1.24.2", features=["rt-multi-thread", "macros"] }
